name: "Setup Spack"
description: "Setup Spack"
inputs:
  ref:
    description: "Version of Spack (git ref: develop, releases/v0.21, ...)"
    required: false
    default: develop
  buildcache:
    description: "Enable the Github Action build cache"
    required: false
    default: "true"
  path:
    description: "Path to Spack"
    required: false
    default: "spack"
runs:
  using: "composite"
  steps:
  - name: Checkout Spack
    uses: actions/checkout@v3
    with:
      repository: spack/spack
      path: ${{ inputs.path }}
      ref: ${{ inputs.ref }}

  - name: Setup Spack
    run: echo "$PWD/spack/bin" >> "$GITHUB_PATH"
    shell: sh

  - name: Setup build cache
    if: ${{ inputs.buildcache == 'true' }}
    run: spack mirror add github-actions-buildcache oci://ghcr.io/spack/github-actions-buildcache
    shell: sh
