name: Development

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ref:
        - develop
        - b35d6d13a7359f42abc1c468ea671fcc0daabffd
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Spack
        uses: ./
        with:
          ref: ${{ matrix.ref }}
          buildcache: true
      - run: spack --version
      - run: spack config blame mirrors
      - run: spack install gmake
