name: Development

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Spack
        uses: ./
      - run: spack --version
      - run: spack config blame mirrors
      - run: spack --backtrace install --reuse gmake
